### ISSUE TITLE
Does the skip layer mean the sample plate that you set when you read the data?

### ISSUE THREAD

**Issue by cyun-404** [wuhuikai/PointCloudSuperResolution#6]
![image](https://user-images.githubusercontent.com/73474866/199486753-2dbf320d-9961-4da6-b1dc-bd6185c9be87.png)

Hello :) I am curious about 'add a skip connection between the input layer and the output layer' in your paper.
Does this part mean the skip rate when data is read in?
I wonder the meaning of "First, we remove the residual connections from the proposed generator, as well as the skip connection between input and output."

**Comment by wuhuikai** [comment]
skip_connection means `y = x + f(x)`.
"First, we remove the residual connections from the proposed generator, as well as the skip connection between input and output.": this is for ablation study, start from a plain network without skip connection.
